apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamboard-data
  namespace: teamboard
spec:
  storageClassName: ebs-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
